Repository thebigsmileXD/MagicWE2, pull requests merged in 2019-12, with the labels that each got.

#164 Update Slovak translation
  resources/lang/slo.ini
Labels: Translation

#162 Add Thai translation
  resources/lang/tha.ini
Labels: Translation

#137 Update German translation as partial fix for #130.
  resources/lang/deu.ini
Labels: Hacktoberfest, State: Ready, Translation

#159 Added Marathi (mar) translations
  resources/lang/mar.ini
Labels: Hacktoberfest, State: Waiting for changes, Translation

#157 Update Georgian translation.
  resources/lang/geo.ini
Labels: Hacktoberfest, Translation

#156 Add Thai translation
  resources/config.yml
  resources/lang/tha.ini
Labels: Hacktoberfest, Translation

#155 add Danish translations
  resources/lang/dan.ini
Labels: Hacktoberfest, Translation

#134 Simplified Chinese Translation
  resources/lang/chi.ini
  resources/lang/zho.ini
Labels: Hacktoberfest, State: In Progress, Translation

#136 Issue #130, new hindi translations
  resources/lang/hin.ini
Labels: Hacktoberfest, State: In Progress, Translation

#140 Update Indonesian translation
  resources/lang/ind.ini
Labels: Hacktoberfest, State: In Analysis, State: In Progress, Translation

#141 Add Estonian language
  resources/lang/est.ini
Labels: Hacktoberfest, State: In Review, Translation

#142 Update swe.ini
  resources/lang/swe.ini
Labels: Hacktoberfest, State: In Progress, Translation

#143 Update portuguese translation
  resources/lang/por.ini
Labels: Hacktoberfest, State: In Review, Translation

#145 Update russian translation
  resources/lang/rus.ini
Labels: Hacktoberfest, State: In Review, Translation

#147 Add Spanish translation
  resources/lang/esp.ini
Labels: Hacktoberfest, State: In Progress, Translation

#149 Updated Greek Translation
  resources/lang/ell.ini
Labels: Hacktoberfest, State: In Progress, Translation

#163 Italian translation
  resources/lang/ita.ini
Labels: Translation

#144 updated french translation
  resources/lang/fre.ini
Labels: Hacktoberfest, State: In Review, Translation

#152 Fix diameter translation
  resources/lang/fre.ini
Labels: Hacktoberfest, State: Ready, Translation

#150 Add Esperanto translation
  resources/lang/epo.ini
Labels: Hacktoberfest, State: In Analysis, State: In Review, Translation

#148 Update dutch language
  resources/lang/nld.ini
Labels: Hacktoberfest, State: In Review, State: Waiting for changes, Translation
