Repository thebigsmileXD/MagicWE2, pull requests merged in 2021-11, with the labels that each got.

#200 add lao Language translate
  resources/lang/lao.ini
Labels: State: Ready, Hacktoberfest, Translation, hacktoberfest-accepted

#201 Update czech translation
  resources/lang/ces.ini
Labels: State: Ready, Hacktoberfest, Translation, hacktoberfest-accepted

#206 Fix various mistranslations (IT)
  resources/lang/ita.ini
Labels: State: Ready, Hacktoberfest, Translation, hacktoberfest-accepted

#208 Update Georgian translation.
  resources/lang/geo.ini
Labels: State: Ready, Hacktoberfest, Translation, hacktoberfest-accepted

#199 Add Ukrainian translation
  resources/lang/ukr.ini
Labels: State: Ready, Hacktoberfest, Translation, hacktoberfest-accepted, TODO cherry pick to PM4

#198 changed: minor improvements to NL translation in Grammar, spelling, a…
  resources/lang/nld.ini
Labels: State: Ready, Hacktoberfest, Translation, hacktoberfest-accepted, TODO cherry pick to PM4

#197 Create pun.ini
  resources/lang/pun.ini
Labels: Invalid, Hacktoberfest, Translation, State: Waiting for changes, TODO cherry pick to PM4
